# Use the latest Ubuntu image from Docker Hub
FROM ubuntu:latest

# update packages and install python
RUN apt-get update

# Example on copying files from project to container
#COPY .devcontainer/example.txt ./example.txt
# open terminal i container and "cd /" and "cat example.txt" to see "TEST!"
# the example.txt got placed in the root folder of the container (not root user folder)
